SAMPLES = ['Sample1', 'Sample2', 'Sample3']

rule all:
    input:
        'test.txt'
       
rule collate_outputs:
    input:
        expand('{sample}.txt', sample = SAMPLES)
    output:
        'test.txt'
    run:
        with open(output[0], 'w') as out:
            for i in input:
                for line in open(i):
                    out.write(i + ', ')
            out.write("are sucessfully processed")

rule quantify_genes:
    input:
        genome = 'genome.fa',
        r1 = 'data/{sample}.R1.fastq.gz',
        r2 = 'data/{sample}.R2.fastq.gz'
    output:
        '{sample}.txt'

    shell:
        'echo {input.genome} {input.r1} {input.r2} > {output}'

        
rule clean:
    shell:
        'rm *.txt'


